### PR TITLE
feat: Storj backend integration

### PR DESCRIPTION
**Pull request by jay-dee7**
### Motivation & Context:

[Storj](https://storj.io) is a brilliant decentralised storage network. Storj is Web3 native and distributed. It has an S3-compatible API and costs only a fraction of what other centralised providers like AWS S3, Azure Blob Storage, Google Cloud Storage charge. 
Storj is the perfect platform to integrate into OpenRegistry so this PR adds the functionality to use Storj as the underlying storage provider for storing container images and their manifests.
 
### Description:

We already had the S3-compatible implementation (via Filebase). We just tweaked it a little bit to make it work with Storj's API.

### Types of Changes:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### PR Checklist:

- [x] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I've read the CONTRIBUTION guide
- [x] I have signed-off my commits with git commit -s

### CODE REVIEW

**Comment by keleffew** [comment]
I wanted to follow-up here to see if there is anything I can do here to help accelerate the Storj integration.  

Is there any issues here preventing this from being merged?  Happy to help.

Thanks,
Kevin

**Comment by jay-dee7** [comment]
> I wanted to follow-up here to see if there is anything I can do here to help accelerate the Storj integration.
> 
> Is there any issues here preventing this from being merged? Happy to help.
> 
> Thanks, Kevin

Hey @keleffew this PR on it's own is good to be merged. The Storj backend itself works fine but it fails with empty layers/super tiny (10 bytes) sized layers. In reality this never happens and we've successfully tested uploading `hello-world` and `busybox` images which are the smallest images available. Push, Pull, Content discovery, and Content management all work fine but one of our tests fail with error being the chunk size is too small for multipart upload. We're working on making it work and pass conformance on CI and then this PR would be good to be merged

**Comment by jtolio** [comment]
A potentially unimportant point - you might be able to sidestep the multipart size minimum limitation if you use our native integration instead of going through our S3 compatible gateways - https://pkg.go.dev/storj.io/uplink is hopefully fairly straightforward and allows uploads and downloads go direct to nodes in our network, instead of through a Gateway layer.  But both options are well supported.

**Comment by jay-dee7** [comment]
Thanks for sharing this @jtolio. I actually did look at `uplink` before going with S3 based implementation. I'm just not familiar with uplink and with our existing implementation, conformance was already `55/59` passing.

However, over the weeks, I explored uplink and I feel we should definitely have an implementation with uplink. Native integrations are  always better IMO. So we'll add an issue for adding `Storj with Uplink` as another backend.

And finally, I've opened up an issue at https://github.com/opencontainers/distribution-spec/issues/374 about our test failing for Push and we'll just wait for them to get back to us before moving on with an implementation.

**Comment by jay-dee7** [comment]
@guacamole the conformance now passes with the changes from https://github.com/opencontainers/distribution-spec/pull/391
I've tested it out with Storj (Uplink) and it works just fine.
Out CI uses `opencontainers/distribution-spec@v1.0.1` action, which lacks the changes we're waiting for.
Once the PR at OCI merges, our CI will start passing automatically.
CC: @keleffew @jtolio

**Review by guacamole — APPROVED** [review]
Awesome, SGTM 🥇

**Pull request merged**
