### PR TITLE
Fix: Use our fork of go-skynet for all Skynet Ops

### LINKED ISSUE #79: update which skynet package is used
currently, https://github.com/containerish/OpenRegistry/blob/c7bc9ba85b92ad1c4b59f5b50caf2a1fe8bac967/skynet/skynet.go#L9 imports from https://github.com/NebulousLabs/go-skynet which appears to be archived an directs users to use https://github.com/SkynetLabs/go-skynet instead

### PR DESCRIPTION
**Pull request by jay-dee7**
Fixes #79 - from here on we use our fork of skynet maintained at
[Containerish's Fork of Skynet Go SDK](https://github.com/containerish/go-skynet.git)

Signed-off-by: jay-dee7 <jasdeepsingh.uppal@gmail.com>

### CODE REVIEW

**Comment by jay-dee7** [comment]
@vbatts I hope it's okay. We're switching to our fork of go-skynet, which is up-to-date with the official implementation of go-skynet

**Review by guacamole — APPROVED** [review]
Looks great!! 💯

**Comment by guacamole** [comment]
Good to merge,
We'll wait for @vbatts to get back to see if he has anything to add..

**Comment by vbatts** [comment]
Oh, no worries from me. I was just browsing over the project, and saw something that could be tidy'ed up 😸

**Comment by jay-dee7** [comment]
Haha thanks a ton. Please let us know if there's something else you noticed (any implementation error, etc) we'd love to fix it up :)

@guacamole lets merge this one?

**Comment by guacamole** [comment]
@jay-dee7 , Awesome!!! Merging it..

**Pull request merged**
